name: pipeline

on:
  push:
    branches:
      - Breno  
  pull_request:
    branches:
      - Breno  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install  

    - name: Run tests
      run: |
        npm test -- --ci --reporters=jest-stare --coverage  

    - name: Build the app
      run: |
        npm run build  

    - name: Deploy to GitHub Pages (Opcional)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  
        publish_dir: ./build
